mode: deployment

replicaCount: 2

image:
  repository: docker.io/otel/opentelemetry-collector-contrib

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  processors:
    memory_limiter:
      check_interval: 5s
      limit_percentage: 80

    batch: {}

  exporters:
    debug:
      verbosity: basic

    otlp/tempo:
      endpoint: tempo.monitoring.svc.cluster.local:4317

      tls:
        insecure: true

    otlphttp/loki:
      endpoint: http://loki.monitoring.svc.cluster.local:3100/otlp

  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [debug, otlp/tempo]

      logs:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [debug, otlphttp/loki]

      metrics:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [debug]
